# Generated by Django 4.1.6 on 2023-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='Created_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
