# Generated by Django 4.1.6 on 2023-03-30 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Job_owner'),
            preserve_default=False,
        ),
    ]
